src/layouts/SecurityLayout.tsx, src/pages/document.ejs, src/pages/user/login2/index.tsx
=> fix(系统配置): 系统配置优化

src/pages/device/visualization/charts/LineChart.tsx
=> fix(可视化): 设备详情中可视化图表日期显示问题

src/pages/device/Instance/Export/index.tsx, src/pages/device/Instance/Import/index.tsx, src/pages/device/Product/Detail/PropertyImport/index.tsx, src/pages/device/Product/service.ts, src/pages/system/Role/Edit/Permission/DataPermission.tsx, src/pages/system/Role/service.ts
=> fix: 角色接口管理

src/pages/device/Instance/Detail/Config/Tags/index.tsx, src/pages/device/Instance/Detail/Config/index.tsx, src/pages/device/Instance/Detail/Info/index.tsx, src/pages/device/Instance/Detail/index.tsx, src/pages/device/Instance/Import/index.tsx, src/pages/device/Instance/Save/index.tsx, src/pages/device/Instance/index.tsx, src/pages/device/Instance/service.ts
=> fix: 设备详情修改

src/pages/link/AccessConfig/Detail/Access/index.less, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/link/AccessConfig/Detail/Provider/index.less, src/pages/link/AccessConfig/Detail/Provider/index.tsx, src/pages/link/AccessConfig/Detail/index.tsx, src/pages/link/AccessConfig/index.less, src/pages/link/AccessConfig/index.tsx, src/pages/link/AccessConfig/service.ts, src/pages/link/AccessConfig/typings.d.ts
=> feat: 设备接入配置

src/pages/device/Product/Detail/Access/index.less, src/pages/device/Product/Detail/Access/index.tsx, src/pages/device/Product/Detail/index.tsx, src/pages/device/Product/service.ts, src/pages/device/Product/typings.d.ts, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/link/AccessConfig/index.tsx
=> feat: 产品设备接入

src/pages/device/Instance/Detail/Running/Property/index.tsx, src/pages/device/Instance/Detail/Running/index.tsx, src/pages/device/Product/Detail/Access/index.less, src/pages/device/Product/Detail/Access/index.tsx, src/pages/link/AccessConfig/Detail/Access/index.less, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/link/AccessConfig/Detail/index.tsx, src/pages/link/AccessConfig/index.less, src/pages/link/AccessConfig/index.tsx, src/pages/link/AccessConfig/service.ts, src/pages/link/Protocol/FileUpload/index.tsx, src/pages/link/Protocol/index.tsx
=> fix: 3.23修改bug

src/pages/device/Instance/Detail/Config/index.tsx, src/pages/device/Product/Detail/Access/AccessConfig/index.tsx, src/pages/device/Product/Detail/Access/index.less, src/pages/device/Product/Detail/Access/index.tsx, src/pages/device/Product/Detail/BaseInfo/index.tsx, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/link/AccessConfig/Detail/index.tsx, src/pages/link/Protocol/index.tsx, src/pages/link/Type/Save/index.tsx
=> fix: 3.24修改bug1

src/pages/device/Instance/Detail/Config/index.tsx, src/pages/device/Instance/Detail/Running/index.tsx, src/pages/device/Instance/Detail/index.tsx, src/pages/device/Product/Detail/BaseInfo/index.tsx, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/link/Protocol/FileUpload/index.tsx, src/pages/link/Protocol/index.tsx, src/pages/link/Type/Save/index.tsx, src/pages/system/Role/Edit/Permission/Allocate/MenuPermission.tsx
=> fix: 物模型显示错误

src/locales/zh-CN/pages.ts, src/pages/device/Instance/Detail/Info/index.tsx, src/pages/device/Product/Detail/BaseInfo/index.tsx, src/pages/link/Protocol/index.tsx
=> fix: 修改产品数量

src/pages/device/Instance/Detail/Running/Event/index.tsx, src/pages/device/Instance/Detail/Running/Property/index.tsx, src/pages/link/Protocol/index.tsx
=> fix: 事件同步更新

src/pages/device/Instance/Detail/index.tsx, src/pages/device/Product/Detail/Access/AccessConfig/index.tsx, src/pages/device/Product/Detail/Access/index.less, src/pages/device/Product/Detail/Access/index.tsx, src/pages/link/AccessConfig/Detail/Access/index.less, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/link/AccessConfig/index.tsx, src/pages/link/Protocol/index.tsx, src/pages/system/Permission/index.tsx, src/pages/system/Role/Edit/Permission/index.tsx, src/pages/system/Role/Edit/UserManage/BindUser.tsx, src/pages/system/Role/Edit/UserManage/index.tsx, src/pages/system/Role/index.tsx
=> fix: 修改bug3.25上午

src/pages/device/Instance/Detail/ChildDevice/BindChildDevice/index.tsx, src/pages/device/Instance/Detail/ChildDevice/index.tsx, src/pages/device/Instance/Detail/Config/index.tsx, src/pages/device/Instance/Detail/Log/index.tsx, src/pages/device/Instance/Detail/index.tsx, src/pages/device/Instance/Export/index.tsx, src/pages/device/Instance/Import/index.tsx, src/pages/device/Instance/service.ts, src/pages/device/Product/Detail/index.tsx, src/pages/link/AccessConfig/Detail/Access/index.less, src/pages/link/Protocol/FileUpload/index.tsx, src/pages/system/Permission/Save/index.tsx, src/pages/system/Permission/index.tsx, src/pages/system/Permission/service.ts, src/pages/system/Role/index.tsx, src/pages/system/User/index.tsx
=> fix: 修改bug3.25下午

src/pages/device/Instance/Detail/Running/Event/index.tsx, src/pages/device/Instance/Detail/Running/Property/PropertyCard.tsx, src/pages/device/Instance/Detail/index.tsx, src/pages/device/Product/Detail/Access/index.tsx, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/link/Protocol/index.tsx, src/pages/system/Permission/Save/index.tsx
=> fix: 3.28修改bug

src/utils/menu/router.ts
=> fix: 修复权限配置路径

src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/rule-engine/Instance/index.tsx, src/pages/system/Role/Detail/Permission/Allocate/MenuPermission.tsx, src/pages/system/Role/Detail/Permission/Allocate/index.tsx, src/pages/system/Role/Detail/Permission/index.tsx, src/utils/util.ts
=> fix: 3.29下午修复bug

src/components/SipComponent/index.tsx, src/components/TitleComponent/index.less, src/components/TitleComponent/index.tsx, src/pages/Log/System/index.tsx, src/pages/device/Product/Detail/Access/index.tsx, src/pages/link/AccessConfig/service.ts, src/pages/media/Stream/Detail/index.tsx, src/pages/media/Stream/index.tsx, src/pages/rule-engine/Instance/index.tsx, src/utils/util.ts
=> fix: 修改流媒体服务bug

src/components/ProTableCard/CardItems/cascade.tsx, src/components/ProTableCard/TableCard.tsx, src/components/SipComponent/index.tsx, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/link/AccessConfig/Detail/Media/index.less, src/pages/link/AccessConfig/Detail/Media/index.tsx, src/pages/link/AccessConfig/Detail/Provider/index.tsx, src/pages/link/AccessConfig/Detail/index.tsx, src/pages/link/AccessConfig/index.less, src/pages/link/AccessConfig/index.tsx, src/utils/menu/index.ts, src/utils/menu/router.ts
=> fix: 4.7上午修改bug

src/components/ProTableCard/CardItems/cascade.tsx, src/pages/Log/System/index.tsx, src/pages/device/Instance/Detail/Running/Property/index.tsx, src/pages/device/Instance/Detail/index.tsx, src/pages/device/Product/Detail/Access/AccessConfig/index.tsx, src/pages/device/Product/Detail/Access/index.tsx, src/pages/link/AccessConfig/Detail/Media/index.tsx, src/pages/link/Protocol/index.tsx, src/pages/media/Cascade/Channel/BindChannel/index.tsx, src/pages/media/Cascade/Channel/index.tsx, src/pages/media/Cascade/Publish/index.tsx, src/pages/media/Cascade/Save/index.tsx, src/pages/media/Cascade/index.tsx, src/pages/media/Cascade/service.ts, src/pages/media/Cascade/typings.d.ts, src/pages/media/Stream/Detail/index.tsx, src/pages/rule-engine/Instance/index.tsx, src/pages/system/Role/Detail/Permission/index.tsx
=> feat: 国标级联

src/pages/device/Product/Detail/Access/AccessConfig/index.tsx, src/pages/device/Product/typings.d.ts, src/pages/link/AccessConfig/Detail/Media/index.tsx, src/pages/media/Cascade/Channel/BindChannel/index.tsx, src/pages/media/Cascade/Channel/index.tsx, src/pages/media/Cascade/index.tsx
=> fix: 4.13修改bug

src/components/SipSelectComponent/index.tsx, src/pages/device/Instance/Detail/MetadataMap/EditableTable/index.tsx, src/pages/link/Protocol/index.tsx, src/pages/media/Cascade/Channel/index.tsx, src/pages/media/Cascade/Save/index.tsx, src/pages/media/Cascade/index.tsx, src/pages/media/Cascade/service.ts, src/pages/media/Stream/Detail/index.tsx
=> fix: 修改国标级联错误

src/components/ProTableCard/CardItems/AccessConfig/index.less, src/components/ProTableCard/CardItems/AccessConfig/index.tsx, src/components/ProTableCard/CardItems/cascade.tsx, src/components/ProTableCard/CardItems/ruleInstance.tsx, src/pages/device/Instance/Detail/Config/index.tsx, src/pages/device/Instance/Detail/Log/index.tsx, src/pages/device/Instance/Detail/MetadataMap/EditableTable/index.tsx, src/pages/device/Instance/Detail/Tags/index.tsx, src/pages/device/Instance/service.ts, src/pages/device/Product/Detail/Access/AccessConfig/index.tsx, src/pages/link/AccessConfig/index.tsx, src/pages/media/Cascade/Channel/index.tsx, src/pages/media/Cascade/index.tsx, src/pages/rule-engine/Instance/index.tsx
=> fix: 修改bug5.37

src/pages/link/AccessConfig/index.tsx, src/pages/link/Protocol/index.tsx, src/pages/media/Cascade/index.tsx, src/pages/rule-engine/Instance/index.tsx, src/pages/system/Permission/index.tsx
=> fix: 启用状态不可删除修改

src/pages/rule-engine/Instance/index.tsx
=> fix: 提交代码设备接入

src/pages/device/Instance/Detail/Diagnose/Status/ManualInspection.tsx, src/pages/device/Instance/Detail/Diagnose/Status/index.tsx, src/pages/device/Instance/Detail/Diagnose/Status/model.ts, src/pages/device/Instance/service.ts, src/pages/link/AccessConfig/service.ts
=> fix: 诊断错误和设备接入

src/pages/media/Cascade/Channel/BindChannel/index.tsx, src/pages/media/Cascade/Channel/index.tsx, src/pages/rule-engine/Alarm/Log/index.tsx, src/pages/rule-engine/Alarm/Log/model.ts
=> feat: 创建告警目录

src/components/FTermArrayCards/index.tsx, src/pages/device/Instance/Detail/Diagnose/Status/ManualInspection.tsx, src/pages/device/Instance/Detail/Diagnose/Status/index.tsx, src/pages/device/Instance/Detail/MetadataMap/EditableTable/index.tsx, src/pages/device/Product/Detail/Access/AccessConfig/index.tsx, src/pages/device/Product/Detail/Access/index.tsx, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/media/Cascade/Channel/index.tsx, src/pages/rule-engine/Alarm/Log/SolveLog/index.tsx, src/pages/rule-engine/Alarm/Log/TabComponent/index.tsx
=> fix: 修改设备诊断bug

src/pages/device/Instance/Detail/Diagnose/Status/index.tsx, src/pages/device/Instance/Detail/Diagnose/Status/model.ts, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/link/Protocol/save/index.tsx, src/pages/notice/Config/SyncUser/index.tsx, src/pages/rule-engine/Alarm/Configuration/Save/index.less, src/pages/rule-engine/Alarm/Configuration/index.tsx, src/pages/rule-engine/Alarm/Configuration/service.ts, src/pages/rule-engine/Alarm/Configuration/typings.d.ts
=> fix: 告警配置修改

src/pages/device/Instance/Detail/Diagnose/Status/index.tsx, src/pages/device/Instance/Detail/Diagnose/Status/model.ts, src/pages/device/Instance/Detail/MetadataMap/EditableTable/index.tsx, src/pages/notice/Config/SyncUser/index.tsx, src/pages/notice/Config/index.tsx, src/pages/notice/Config/service.ts
=> fix: 修改物模型映射

src/components/ProTableCard/TableCard.tsx, src/pages/rule-engine/Alarm/Configuration/index.tsx
=> fix: 修改bug

src/pages/device/Instance/Detail/Config/index.tsx, src/pages/device/Instance/Detail/Diagnose/Status/index.tsx, src/pages/device/Instance/Detail/Diagnose/Status/model.ts, src/pages/device/Instance/Detail/MetadataLog/Property/index.tsx, src/pages/link/AccessConfig/Detail/Access/index.tsx, src/pages/notice/Config/BindUser/index.tsx, src/pages/rule-engine/Alarm/Configuration/Save/index.tsx, src/pages/rule-engine/Alarm/Configuration/index.tsx, src/pages/rule-engine/Alarm/Log/Detail/Info.tsx, src/pages/rule-engine/Alarm/Log/Detail/index.tsx, src/pages/rule-engine/Alarm/Log/SolveComponent/index.tsx, src/pages/rule-engine/Alarm/Log/TabComponent/index.less, src/pages/rule-engine/Alarm/Log/TabComponent/index.tsx, src/pages/rule-engine/Alarm/Log/index.tsx, src/pages/rule-engine/Alarm/Log/model.ts, src/utils/menu/router.ts
=> fix: 修改告警记录

src/pages/device/Instance/Detail/MetadataLog/Property/index.tsx
=> fix: 修改运行状态

src/components/ProTableCard/CardItems/AlarmConfig.tsx, src/pages/device/Instance/Detail/Diagnose/index.tsx, src/pages/notice/Config/BindUser/index.tsx, src/pages/rule-engine/Alarm/Configuration/index.tsx, src/pages/rule-engine/Alarm/Configuration/service.ts, src/pages/rule-engine/Alarm/Log/SolveLog/index.tsx, src/pages/rule-engine/Alarm/Log/TabComponent/index.less, src/pages/rule-engine/Alarm/Log/TabComponent/index.tsx
=> fix: 修改告警配置卡片页面

src/pages/device/Instance/Detail/Running/Property/EditProperty.tsx, src/pages/device/Instance/Detail/Running/Property/PropertyCard.tsx, src/pages/device/Instance/Detail/Running/Property/PropertyTable.tsx, src/pages/device/Instance/Detail/Running/Property/index.tsx
=> fix: 修改运行状态卡顿的问题

src/components/ProTableCard/CardItems/AlarmConfig.tsx, src/pages/device/Instance/Detail/MetadataLog/Property/AMap.tsx, src/pages/device/Instance/Detail/MetadataLog/Property/Charts.tsx, src/pages/device/Instance/Detail/MetadataLog/Property/index.tsx, src/pages/device/Instance/Detail/Running/Property/FileComponent/index.less, src/pages/device/Instance/Detail/Running/Property/FileComponent/index.tsx, src/pages/device/Instance/Detail/Running/Property/index.tsx, src/pages/device/Instance/service.ts, src/pages/device/Product/Detail/Access/AccessConfig/index.tsx, src/pages/link/Certificate/index.tsx, src/pages/rule-engine/Alarm/Configuration/index.tsx
=> fix: 修改运行状态样式

src/pages/Northbound/AliCloud/Detail/index.tsx
=> fix: 阿里云instanceId

src/components/AMapComponent/hooks/Distance.tsx, src/components/ProTableCard/CardItems/AlarmConfig.tsx, src/components/ProTableCard/CardItems/noticeConfig.tsx, src/components/ProTableCard/CardItems/noticeTemplate.tsx, src/pages/device/Instance/Detail/Tags/location/AMap.tsx, src/pages/notice/Config/index.tsx, src/pages/notice/Template/index.tsx, src/pages/rule-engine/Alarm/Configuration/index.tsx
=> fix: 2个点轨迹问题

src/pages/link/Certificate/index.tsx
=> fix: common

src/pages/device/Instance/Detail/Diagnose/index.less, src/pages/device/Instance/Detail/Diagnose/index.tsx, src/pages/device/Instance/Detail/Running/Property/PropertyCard.tsx
=> fix: 修改诊断样式

src/pages/rule-engine/Alarm/Config/index.less, src/pages/rule-engine/Alarm/Config/index.tsx
=> fix: 修改告警基础配置

src/pages/system/DataSource/Management/EditTable.tsx
=> fix: 修改数据源

src/components/NoticeIcon/NoticeIcon.tsx, src/components/NoticeIcon/NoticeList.tsx, src/components/NoticeIcon/index.tsx, src/components/RightContent/index.tsx, src/pages/account/NotificationRecord/index.tsx, src/pages/device/Product/Detail/Access/AccessConfig/index.tsx, src/pages/link/AccessConfig/Detail/Cloud/OneNet/index.tsx, src/pages/link/Protocol/FileUpload/index.tsx, src/services/ant-design-pro/typings.d.ts, src/services/notice/index.ts
=> fix: 右上角无消息通知提示

src/components/FMonacoEditor/index.tsx, src/pages/device/Instance/Detail/Config/index.tsx, src/pages/device/Instance/Detail/MetadataMap/EditableTable/index.tsx, src/pages/device/Instance/Detail/index.tsx, src/pages/link/Type/Detail/index.less, src/pages/link/Type/Detail/index.tsx
=> fix: 修改网络组件tcp
